package com.hoang.basis.yukihon.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    BAD_CREDENTIALS,
    BAD_REQUEST,
    NOT_FOUND,
    CONFLICT,
    ACCESS_DENIED,
    UNAUTHORIZED,
    AUTHENTICATION_REQUIRED,
    TOKEN_EXPIRED,
    TOKEN_INVALID,
    SERVICE_UNAVAILABLE,
    INTERNAL_ERROR
}
